### ISSUE TITLE
[proposal] make another development stream - which does NOT use installing script

### ISSUE THREAD

**Issue by nisshiee** [itamae-plugins/itamae-plugin-recipe-datadog#3]
Currently, you use installing script provided by datadog officially. I think this approaching has both merits and demerits.

- Pros
    - We don't have to anything when datadog changes installation process
- Cons
    - It's hard to keep idempotency

So my proposal is dividing main development stream into 2 streams - one is the same, the other has new approaching.
New approaching is implementing the same procedure as installing script. It contains only installing datadog-agent with package manager, creating default datadog.conf, and restarting agent. It can be very simple code with itamae. If do so, we can fully manage datadog.conf in itamae layer.

**Comment by pataiji** [comment]
Although your idea is nice, I think that is troublesome because we have to implement logic that support multiple linux distros like debian, centos, suse and so on by ourselves.

So I propose the other approach.

```ruby 
execute 'install datadog-agent' do
  if node[:datadog][:install_only]
    command "DD_API_KEY=#{node[:datadog][:api_key]} DD_INSTALL_ONLY=true ./install_agent.sh"
  else
    command "DD_API_KEY=#{node[:datadog][:api_key]} ./install_agent.sh"
  end
  not_if run_specinfra(:check_package_is_installed, 'datadog-agent')
end
```

It has only difference to check datadog-agent has already installed.
And you can change datadog.conf after this, if you need.

(It maybe can't run rightly because this is just sample.)

**Comment by takanamito** [comment]
@nisshiee 
Thank you for your proposal.

I agree with @pataiji . 2 streams in 1 gem is complicated.
and I am thinking to rely on official install script which supports multi platform.

Certainly current implementation has some not good points.

- download install script every time
- same with executing install

So I think I will fix these points.
